loglevel: info
providers:
  - providerType: "azuredevops"
    repositories:
      - "project/repo"
    extraConfig:
      organizationUrl: "https://dev.azure.com/myorg"
      pat: "xxxxxxxxxx"
  - providerType: "github"
    repositories:
      - "owner/repo"
    extraConfig:
      pat: "xxxxxxxxxx"
  - providerType: "bitbucketv1"
    repositories:
      - "owner/repo"
    extraConfig:
      baseUrl: "http://localhost:7990/rest"
      pat: "xxxxxxxxxx"
